### ISSUE TITLE
sh: 1: aprs: not found

### ISSUE THREAD

**Issue by Nodeswitch** [trasukg/watch-aprs#1]
Hey! Thought I'd give this a go, but I'm encountering the following error when I run `watch-aprs /dev/ttyUSB0 9600`.

`sh: 1: aprs: not found`

I have a TNC attached via USB.

Running on the below versions.

```
$ npm -v && nodejs -v 
6.1.0
v10.3.0
```
I didn't encounter any errors when installing. Am I missing anything?

Thanks!

**Comment by trasukg** [comment]
That’s kind of funny shell error.  It seems to be saying it can’t find a command or file called ‘aprs’. It’s also funny that your ‘node’ compiler seems to be called ‘nodejs’ rather than ‘node’. What’s the operating system and is it a standard Node installation (i.e. the download files from ‘nodejs.org’) or is it an operating system package?

I’ll confess I happen to be running Node 8.9.4 on the MacBook that I do most of my development on, so I’ve never tested with the 10.x series, but there really shouldn’t be any problems - The thing that usually changes between versions is the V8 JavaScript engine’s version, and the error your seeing doesn’t look like it’s coming out of the V8 engine.

Could you copy/paste the full terminal output of the command, including the command line that you entered?  I’m sure we can figure it out.

Cheers,

Greg Trasuk, VA3TSK
